In [ ]:
import numpy as np

In [ ]:
print(np.zeros((16, 4), dtype = int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
tot_states = 16
tot_actions = 4
tar_state = 15

q_table = np.zeros((tot_states, tot_actions))
q_table

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
import numpy as np

# Define the environment
n_states = 16  # Number of states in the grid world
n_actions = 4  # Number of possible actions (up, down, left, right)
goal_state = 1  # Goal state

# Initialize Q-table with zeros
Q_table = np.zeros((n_states, n_actions))

# Define parameters
learning_rate = 0.75
discount_factor = 0.92
exploration_prob = 0.3
epochs = 1000


In [ ]:
# Q-learning algorithm
for epoch in range(epochs):
    current_state = np.random.randint(0, n_states)  # Start from a random state

    while current_state != goal_state:
        # Choose action with epsilon-greedy strategy
        if np.random.rand() < exploration_prob:
            action = np.random.randint(0, n_actions)  # Explore
        else:
            action = np.argmax(Q_table[current_state])  # Exploit

        # Simulate the environment (move to the next state)
        # For simplicity, move to the next state
        next_state = (current_state + 1) % n_states

        # Define a simple reward function (1 if the goal state is reached, 0 otherwise)
        reward = 1 if next_state == goal_state else 0

        # Update Q-value using the Q-learning update rule
        Q_table[current_state, action] += learning_rate * \
            (reward + discount_factor *
             np.max(Q_table[next_state]) - Q_table[current_state, action])

        current_state = next_state  # Move to the next state

# After training, the Q-table represents the learned Q-values
print("Learned Q-table:")
print(Q_table)


Learned Q-table:
[[1.         1.         1.         1.        ]
 [0.         0.         0.         0.        ]
 [0.31119283 0.30997723 0.31117383 0.30633044]
 [0.33823058 0.33823243 0.33825308 0.338253  ]
 [0.36766639 0.36766639 0.36766637 0.36766639]
 [0.39963738 0.39963738 0.39963738 0.39963738]
 [0.43438845 0.43438845 0.43438845 0.43438845]
 [0.47216136 0.47216136 0.47216136 0.47216136]
 [0.51321887 0.51321887 0.51321887 0.51321887]
 [0.5578466  0.5578466  0.5578466  0.5578466 ]
 [0.606355   0.606355   0.606355   0.606355  ]
 [0.65908152 0.65908152 0.65908152 0.65908152]
 [0.71639296 0.71639296 0.71639296 0.71639296]
 [0.778688   0.778688   0.778688   0.778688  ]
 [0.8464     0.8464     0.8464     0.8464    ]
 [0.92       0.92       0.92       0.92      ]]


In [ ]:
# n+=1 = n=n+1
q_table[11, 3]

0.0